## Link Images to CSV Data

In [21]:
import os
import numpy as np
import pandas as pd

In [22]:
csv_path = r"C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanManh\Fashion-Marketing-Automation-Solutions\data\processed\posts.csv"

image_folder = r"C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanManh\Fashion-Marketing-Automation-Solutions\images\original_images"

In [23]:
data = pd.read_csv(csv_path)
data.head()

,post_id,timestamp,ownerUsername,type,caption,hashtags,likesCount,commentsCount,image
0,1,2023-06-02 16:34:43+00:00,maryleest,Sidecar,Cannes 2023 with @kilianparis 🤍 #KilianCannes ...,KilianCannes,32070,142,https://scontent-ord5-1.cdninstagram.com/v/t51...
1,2,2023-01-01 07:49:16+00:00,tinaabeysekara,Sidecar,"As the clock struck midnight to ring in 2022, ...",NaN,6565,86,https://instagram.fyei4-1.fna.fbcdn.net/v/t51....
2,3,2023-05-29 18:57:51+00:00,maryleest,Sidecar,The famous stairs 🤎 Photo @gustave_durin Dre...,NaN,28936,123,https://instagram.fpeg1-2.fna.fbcdn.net/v/t51....
3,4,2023-03-07 19:30:42+00:00,stephaniebroek,Sidecar,I visualized this moment so many times before....,CHANELFallWinter,4764,215,https://scontent-lhr8-1.cdninstagram.com/v/t51...
4,5,2023-05-23 21:11:12+00:00,maryleest,Sidecar,Got to witness such historical moment in cinem...,CannesFilmFestival,13379,123,https://instagram.fprg5-1.fna.fbcdn.net/v/t51....

In [24]:
data['local_image_path'] = data['post_id'].apply(lambda x: os.path.join(image_folder, f"{x}.jpg"))

data.drop(columns=['image'], inplace=True)

In [25]:
data.head()

,post_id,timestamp,ownerUsername,type,caption,hashtags,likesCount,commentsCount,local_image_path
0,1,2023-06-02 16:34:43+00:00,maryleest,Sidecar,Cannes 2023 with @kilianparis 🤍 #KilianCannes ...,KilianCannes,32070,142,C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...
1,2,2023-01-01 07:49:16+00:00,tinaabeysekara,Sidecar,"As the clock struck midnight to ring in 2022, ...",NaN,6565,86,C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...
2,3,2023-05-29 18:57:51+00:00,maryleest,Sidecar,The famous stairs 🤎 Photo @gustave_durin Dre...,NaN,28936,123,C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...
3,4,2023-03-07 19:30:42+00:00,stephaniebroek,Sidecar,I visualized this moment so many times before....,CHANELFallWinter,4764,215,C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...
4,5,2023-05-23 21:11:12+00:00,maryleest,Sidecar,Got to witness such historical moment in cinem...,CannesFilmFestival,13379,123,C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...

In [26]:
print(data[['post_id', 'local_image_path']].head())

   post_id                                   local_image_path
0        1  C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...
1        2  C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...
2        3  C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...
3        4  C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...
4        5  C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanMan...

In [ ]:
from tensorflow.keras.preprocessing.image import load_img, img_to_array

def preprocess_image(image_path, target_size=(224, 224)):
    """
    Đọc ảnh, resize về kích thước target_size và normalize pixel.
    """
    try:
        img = load_img(image_path, target_size=target_size)
        img_array = img_to_array(img)
        img_array = img_array / 255.0
        return img_array
    except Exception as e:
        print(f"Error processing image {image_path}: {e}")
        return None

# Ví dụ xử lý ảnh đầu tiên
sample_img = preprocess_image(data['local_image_path'].iloc[0])
print("Kích thước ảnh sau xử lý:", sample_img.shape)

Kích thước ảnh sau xử lý: (224, 224, 3)