In [20]:
import pandas as pd
import matplotlib.pyplot as plt
import re
import emoji
import nltk

In [21]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ADMIN\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [22]:
posts_path =r"C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanManh\Fashion-Marketing-Automation-Solutions\data\processed\processed_posts_df.csv"
comments_path = r"C:\Users\ADMIN\Desktop\ITDSIU21099_HoangVanManh\Fashion-Marketing-Automation-Solutions\data\processed\processed_comments_df.csv"

In [23]:
posts_df = pd.read_csv(posts_path)
comments_df = pd.read_csv(comments_path)

In [24]:
posts_df.head()

,post_id,postUser,timestamp,combined_tokens,likesCount,commentsCount
0,1,maryleest,2023-06-02 16:34:43+00:00,"['cannes', '2023', 'kilianparis', 'kiliancanne...",32070,142
1,2,tinaabeysekara,2023-01-01 07:49:16+00:00,"['clock', 'struck', 'midnight', 'ring', '2022'...",6565,86
2,3,maryleest,2023-05-29 18:57:51+00:00,"['famous', 'stairs', 'photo', 'gustave_durin',...",28936,123
3,4,stephaniebroek,2023-03-07 19:30:42+00:00,"['visualized', 'moment', 'many', 'times', 'fir...",4764,215
4,5,maryleest,2023-05-23 21:11:12+00:00,"['got', 'witness', 'historical', 'moment', 'ci...",13379,123

In [25]:
posts_df.head()

,post_id,postUser,timestamp,combined_tokens,likesCount,commentsCount
0,1,maryleest,2023-06-02 16:34:43+00:00,"['cannes', '2023', 'kilianparis', 'kiliancanne...",32070,142
1,2,tinaabeysekara,2023-01-01 07:49:16+00:00,"['clock', 'struck', 'midnight', 'ring', '2022'...",6565,86
2,3,maryleest,2023-05-29 18:57:51+00:00,"['famous', 'stairs', 'photo', 'gustave_durin',...",28936,123
3,4,stephaniebroek,2023-03-07 19:30:42+00:00,"['visualized', 'moment', 'many', 'times', 'fir...",4764,215
4,5,maryleest,2023-05-23 21:11:12+00:00,"['got', 'witness', 'historical', 'moment', 'ci...",13379,123

In [26]:
posts_df['combined_tokens'] = posts_df['combined_tokens'].apply(lambda x: ' '.join(x))